# Generated by Django 5.1 on 2024-08-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
